---
language: java
dist: bionic

jdk:
  - openjdk8

notifications:
  email: true

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
    - stage: Build and run tests
    - stage: Run system test with template
      script:
        - git clone https://github.ibm.com/CloudEngineering/sdkgen-systest.git
        - cd sdkgen-systest
        - ./install_scripts/install_deps_ubuntu.sh
        - ./setup_and_generate.sh -l ibm-java -t $TRAVIS_BRANCH -s

before_install:
- sudo apt-get update
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc

install: true

script:
-  mvn clean verify $MVN_ARGS
